---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-mount-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: sqlite-mount-pv
    nodeStageSecretRef:
      name: sqlite-ceph
      namespace: default
    nodePublishSecretRef:
      name: sqlite-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.201:6789
      rootPath: /containervolumes
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-mount-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: sqlite-mount-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlite
  labels:
    app: sqlite
spec:
  selector:
    matchLabels:
      app: sqlite # has to match .spec.template.metadata.labels
  serviceName: "sqlite"
  replicas: 0
  template:
    metadata:
      labels:
        app: sqlite # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sqlite
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        image: keinos/sqlite3:latest
        volumeMounts:
        - name: sqlite-mount
          mountPath: /containervolumes
      volumes:
      - name: sqlite-mount
        persistentVolumeClaim:
          claimName: sqlite-mount-pvc
          readOnly: false
