---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "8b31840b-5706-4c92-8135-0d6e03976af1",
        "monitors": [
          "192.168.1.131:6789",
          "192.168.1.132:6789",
          "192.168.1.133:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: ceph-csi-rbd
