apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/metallb/metallb-operator.git
    targetRevision: HEAD
    path: bin/metallb-operator.yml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
