spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/dustinmhorvath/k8s_workspace.git
    targetRevision: HEAD
    path: deployments/argo
  syncPolicy:
    syncOptions:
    - PrunePropagationPolicy=foreground
    automated:
      prune: true
      selfHeal: true
