---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  ports:
  - port: 80
    targetPort: 8123
    name: homeassistant
  selector:
    app: homeassistant
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: homeassistant-config-pv
    nodeStageSecretRef:
      name: homeassistant-ceph
      namespace: default
    nodePublishSecretRef:
      name: homeassistant-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.201:6789
      rootPath: /containervolumes/homeassistant
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: homeassistant-config-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant # has to match .spec.template.metadata.labels
  serviceName: "homeassistant"
  replicas: 1
  template:
    metadata:
      labels:
        app: homeassistant # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant
        env:
        - name: TZ
          value: America/Chicago
        ports:
        - containerPort: 8123
          name: homeassistant
        volumeMounts:
        - name: homeassistant-config
          mountPath: /config
      volumes:
      - name: homeassistant-config
        persistentVolumeClaim:
          claimName: homeassistant-config-pvc
          readOnly: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  labels:
    app: homeassistant
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  rules:
  - host: homeassistant.perihelion.host
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: homeassistant
            port:
              number: 80
  tls:
  - hosts:
    - homeassistant.perihelion.host
    secretName: homeassistant.perihelion.host
