---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  labels:
    app: jellyseerr
spec:
  ports:
  - port: 80
    targetPort: 5055
    name: jellyseerr
  selector:
    app: jellyseerr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-config-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: jellyseerr-config-pv
    nodeStageSecretRef:
      name: jellyseerr-ceph
      namespace: default
    nodePublishSecretRef:
      name: jellyseerr-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.131:6789,192.168.1.132:6789,192.168.1.133:6789
      rootPath: /docker/jellyseerr
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: jellyseerr-config-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyseerr
  labels:
    app: jellyseerr
spec:
  selector:
    matchLabels:
      app: jellyseerr # has to match .spec.template.metadata.labels
  serviceName: "jellyseerr"
  replicas: 1
  template:
    metadata:
      labels:
        app: jellyseerr # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: jellyseerr
        image: fallenbagel/jellyseerr:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Chicago
        - name: PUID
          value: '911'
        - name: PGID
          value: '911'
        ports:
        - containerPort: 7878
          name: jellyseerr
        volumeMounts:
        - name: jellyseerr-config
          mountPath: /app/config
      volumes:
      - name: jellyseerr-config
        persistentVolumeClaim:
          claimName: jellyseerr-config-pvc
          readOnly: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr
  labels:
    app: jellyseerr
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  rules:
  - host: requests.perihelion.host
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jellyseerr
            port:
              number: 80
  tls:
  - hosts:
    - requests.perihelion.host
    secretName: requests.perihelion.host
