---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  ports:
  - port: 80
    targetPort: 9696
    name: prowlarr
  selector:
    app: prowlarr
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-downloads-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: prowlarr-downloads-pv
    nodeStageSecretRef:
      name: prowlarr-ceph
      namespace: default
    nodePublishSecretRef:
      name: prowlarr-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.201:6789
      rootPath: /downloads
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-downloads-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: prowlarr-downloads-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: prowlarr-config-pv
    nodeStageSecretRef:
      name: prowlarr-ceph
      namespace: default
    nodePublishSecretRef:
      name: prowlarr-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.201:6789
      rootPath: /containervolumes/prowlarr
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: prowlarr-config-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr # has to match .spec.template.metadata.labels
  serviceName: "prowlarr"
  replicas: 1
  template:
    metadata:
      labels:
        app: prowlarr # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:develop
        env:
          - name: TZ
            value: America/Chicago
        ports:
        - containerPort: 9696
          name: prowlarr
        volumeMounts:
        - name: prowlarr-config
          mountPath: /config
        - name: prowlarr-downloads
          mountPath: /downloads
      volumes:
      - name: prowlarr-config
        persistentVolumeClaim:
          claimName: prowlarr-config-pvc
          readOnly: false
      - name: prowlarr-downloads
        persistentVolumeClaim:
          claimName: prowlarr-downloads-pvc
          readOnly: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  labels:
    app: prowlarr
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: prowlarr.perihelion.host
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: prowlarr
            port:
              number: 80
  tls:
  - hosts:
    - prowlarr.perihelion.host
    secretName: prowlarr.perihelion.host
