---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redbot-config-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: redbot-config-pv
    nodeStageSecretRef:
      name: redbot-ceph
      namespace: default
    nodePublishSecretRef:
      name: redbot-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.131:6789,192.168.1.132:6789,192.168.1.133:6789
      rootPath: /docker/redbot
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redbot-config-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: redbot-config-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redbot
  labels:
    app: redbot
spec:
  selector:
    matchLabels:
      app: redbot # has to match .spec.template.metadata.labels
  serviceName: "redbot"
  replicas: 1
  template:
    metadata:
      labels:
        app: redbot # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redbot
        image: phasecorex/red-discordbot:latest
        imagePullPolicy: Always
        env:
          # TODO: Get this from k8s secret instead, since sensitive
#        - name: TOKEN
#          value: ""
        - name: PREFIX
          value: '!'
        - name: TZ
          value: America/Chicago
        volumeMounts:
        - name: redbot-config
          mountPath: /data
      volumes:
      - name: redbot-config
        persistentVolumeClaim:
          claimName: redbot-config-pvc
          readOnly: false

