---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  #annotations:
  #  metallb.universe.tf/allow-shared-ip: "shared-192.168.1.211"
spec:
  selector:
    app: satisfactory
  ports:
    - name: sftry-7777
      port: 7777
      protocol: UDP
      targetPort: sftry-7777
    - name: sftry-15000
      port: 15000
      protocol: UDP
      targetPort: sftry-15000
    - name: sftry-15777
      port: 15777
      protocol: UDP
      targetPort: sftry-15777
  loadBalancerIP: 192.168.1.212
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: satisfactory-config-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: satisfactory-config-pv
    nodeStageSecretRef:
      name: satisfactory-ceph
      namespace: default
    nodePublishSecretRef:
      name: satisfactory-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.201:6789
      rootPath: /containervolumes/satisfactory/
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-config-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: satisfactory-config-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: satisfactory
spec:
  selector:
    matchLabels:
      app: satisfactory # has to match .spec.template.metadata.labels
  serviceName: "satisfactory"
  replicas: 1
  template:
    metadata:
      labels:
        app: satisfactory # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 30
#      nodeSelector:
#        exclusive: "yes"
#      tolerations:
#      - key: "exclusive"
#        operator: "Equal"
#        value: "yes"
#        effect: "NoSchedule"
      containers:
      - name: satisfactory
        image: wolveix/satisfactory-server:latest
        imagePullPolicy: Always
        ports:
          - name: sftry-7777
            containerPort: 7777
            protocol: UDP
          - name: sftry-15000
            containerPort: 15000
            protocol: UDP
          - name: sftry-15777
            containerPort: 15777
            protocol: UDP
        env:
        - name: DEBUG
          value: "false"
        - name: TZ
          value: America/Chicago
        - name: "STEAMBETA"
          value: "true"
        - name: SKIPUPDATE
          value: "false"
        - name: AUTOSAVEINTERVAL
          value: "600"
        - name: NETWORKQUALITY
          value: "5"
        - name: MAXTICKRATE
          value: "60"
        volumeMounts:
        - name: satisfactory-config
          mountPath: /config/
        #- name: host-mount-satisfactory
        #  mountPath: /config
      volumes:
      #- name: host-mount-satisfactory
      #  hostPath:
      #    path: /var/satisfactory
      - name: satisfactory-config
        persistentVolumeClaim:
          claimName: satisfactory-config-pvc
          readOnly: false
