apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  ports:
  - port: 80
    targetPort: 9091
    name: transmission
  selector:
    app: transmission
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: transmission-downloads-pv
    nodeStageSecretRef:
      name: transmission-ceph
      namespace: default
    nodePublishSecretRef:
      name: transmission-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.131:6789,192.168.1.132:6789,192.168.1.133:6789
      rootPath: /downloads
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: transmission-downloads-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: transmission-config-pv
    nodeStageSecretRef:
      name: transmission-ceph
      namespace: default
    nodePublishSecretRef:
      name: transmission-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.131:6789,192.168.1.132:6789,192.168.1.133:6789
      rootPath: /docker/transmission
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: transmission-config-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  selector:
    matchLabels:
      app: transmission # has to match .spec.template.metadata.labels
  serviceName: "transmission"
  replicas: 1
  template:
    metadata:
      labels:
        app: transmission # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: transmission
        image: linuxserver/transmission:latest
        env:
          - name: TZ
            value: America/Chicago
          - name: USER
            value: "dustin"
          - name: PASS
            valueFrom:
              secretKeyRef:
                name: transmission-pw
                key: password
        ports:
        - containerPort: 9091
          name: transmission
        volumeMounts:
        - name: transmission-config
          mountPath: /config
        - name: transmission-downloads
          mountPath: /downloads
      volumes:
      - name: transmission-config
        persistentVolumeClaim:
          claimName: transmission-config-pvc
          readOnly: false
      - name: transmission-downloads
        persistentVolumeClaim:
          claimName: transmission-downloads-pvc
          readOnly: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  labels:
    app: transmission
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  rules:
  - host: torrent.perihelion.host
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: transmission
            port:
              number: 80
  tls:
  - hosts:
    - torrent.perihelion.host
    secretName: torrent.perihelion.host
