authentik:
  secret_key:
    valueFrom:
      secretKeyRef:
        name: authentik-secret-key
        key: secret-key
  error_reporting:
    enabled: true
  postgresql:
    password:
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-password
          key: password

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - auth.perihelion.host
    annotations:
      # Example annotations to add Homepage to your Homepage!
      #gethomepage.dev/enabled: "true"
      #gethomepage.dev/name: "Homepage"
      #gethomepage.dev/description: "Dynamically Detected Homepage"
      #gethomepage.dev/group: "Dynamic"
      #gethomepage.dev/icon: "homepage.png"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: auth.perihelion.host
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - auth.perihelion.host
        secretName: auth-perihelion-host

postgresql:
  enabled: true
  auth:
    password:
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-password
          key: password
redis:
  enabled: true

