global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret-key
          key: secret-key
      # Doing my best to parse through the horrendously shit documentation on Authentik's configuration page for these vars. I'm trying to cobble these together from a lot of conflicting examples at https://docs.goauthentik.io/docs/install-config/configuration/#postgresql-settings and the actual chart here https://github.com/goauthentik/helm/blob/main/charts/authentik/values.yaml
    - name: AUTHENTIK_POSTGRES__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-password
          key: password
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-password
          key: password
authentik:
  error_reporting:
    enabled: true

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    annotations:
      # Example annotations to add Homepage to your Homepage!
      #gethomepage.dev/enabled: "true"
      #gethomepage.dev/name: "Homepage"
      #gethomepage.dev/description: "Dynamically Detected Homepage"
      #gethomepage.dev/group: "Dynamic"
      #gethomepage.dev/icon: "homepage.png"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: auth.perihelion.host
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - auth.perihelion.host
        secretName: auth-perihelion-host

postgresql:
  enabled: true
redis:
  enabled: true

