---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
spec:
  project: default
  sources:
  - chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.*
    helm:
      releaseName: cnpg
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg-system

