apiVersion: v1
kind: Service
metadata:
  name: deluge
  labels:
    app: deluge
spec:
  ports:
  - port: 80
    targetPort: 8112
    name: deluge
  selector:
    app: deluge
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-downloads-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: deluge-downloads-pv
    nodeStageSecretRef:
      name: deluge-ceph
      namespace: default
    nodePublishSecretRef:
      name: deluge-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.131:6789,192.168.1.132:6789,192.168.1.133:6789
      rootPath: /downloads
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-downloads-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: deluge-downloads-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-config-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: deluge-config-pv
    nodeStageSecretRef:
      name: deluge-ceph
      namespace: default
    nodePublishSecretRef:
      name: deluge-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.131:6789,192.168.1.132:6789,192.168.1.133:6789
      rootPath: /docker/deluge
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: deluge-config-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deluge
  labels:
    app: deluge
spec:
  selector:
    matchLabels:
      app: deluge # has to match .spec.template.metadata.labels
  serviceName: "deluge"
  replicas: 0
  template:
    metadata:
      labels:
        app: deluge # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: deluge
        image: linuxserver/deluge:latest
        env:
          - name: TZ
            value: America/Chicago
        ports:
        - containerPort: 8112
          name: deluge
        volumeMounts:
        - name: deluge-config
          mountPath: /config
        - name: deluge-downloads
          mountPath: /downloads
      volumes:
      - name: deluge-config
        persistentVolumeClaim:
          claimName: deluge-config-pvc
          readOnly: false
      - name: deluge-downloads
        persistentVolumeClaim:
          claimName: deluge-downloads-pvc
          readOnly: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deluge
  labels:
    app: deluge
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  rules:
  - host: torrent.perihelion.host
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: deluge
            port:
              number: 80
  tls:
  - hosts:
    - torrent.perihelion.host
    secretName: torrent.perihelion.host
