---
apiVersion: v1
kind: Service
metadata:
  name: simplex
#  annotations:
#    metallb.universe.tf/allow-shared-ip: "shared-192.168.1.214"
spec:
  selector:
    app: simplex
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
#  loadBalancerIP: 192.168.1.214
#  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplex-configs-pvc
  namespace: default
spec:
  storageClassName: csi-rbd-sc
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #volumeName: simplex-configs-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplex-state-pvc
  namespace: default
spec:
  storageClassName: csi-rbd-sc
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #volumeName: simplex-state-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simplex
spec:
  selector:
    matchLabels:
      app: simplex
  serviceName: "simplex"
  replicas: 1
  template:
    metadata:
      labels:
        app: simplex # has to match .spec.selector.matchLabels
    spec:
      #hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet
    
      nodeSelector:
        restriction_class: gameserver
    
      tolerations:
      - key: "restriction_class"
        operator: "Equal"
        value: "gameserver"
        effect: "NoSchedule"

      terminationGracePeriodSeconds: 30
      containers:
      - name: simplex
        image: simplexchat/smp-server:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5223
            protocol: TCP
        env:
        - name: ADDR
          value: "simplex.perihelion.host"
        - name: CERT_PATH
          value: "certificates"

        volumeMounts:
        - name: simplex-configs
          mountPath: /etc/opt/simplex
        - name: simplex-state
          mountPath: /var/opt/simplex
        - name: simplex-certs
          mountPath: "/certificates"
          readOnly: true

      volumes:
      - name: simplex-configs
        persistentVolumeClaim:
          claimName: simplex-configs-pvc
      - name: simplex-state
        persistentVolumeClaim:
          claimName: simplex-state-pvc
      - name: simplex-certs
        secret:
          secretName: simplex.perihelion.host
          items:
            - key: tls.key
              path: simplex.perihelion.host.key
            - key: tls.crt
              path: simplex.perihelion.host.crt
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplex
  labels:
    app: simplex
    gethomepage.dev/enabled: "true"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    cert-manager.io/private-key-size: "4096"

    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  rules:
  - host: simplex.perihelion.host
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: simplex
            port:
              number: 443
#  tls:
#  - hosts:
#    - simplex.perihelion.host
#    secretName: simplex.perihelion.host
