---
apiVersion: v1
kind: Service
metadata:
  name: factorio-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-192.168.1.211"
spec:
  selector:
    app: factorio
  ports:
    - name: factorio-34197u
      port: 34197
      protocol: UDP
      targetPort: factorio-34197u
  loadBalancerIP: 192.168.1.211
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-config-pvc
  namespace: default
spec:
  storageClassName: csi-rbd-sc
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #volumeName: factorio-config-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: factorio
spec:
  selector:
    matchLabels:
      app: factorio # has to match .spec.template.metadata.labels
  serviceName: "factorio"
  replicas: 1
  template:
    metadata:
      labels:
        app: factorio # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: factorio
        image: factoriotools/factorio:stable
        imagePullPolicy: Always
        ports:
          - name: factorio-34197
            containerPort: 34197
            protocol: UDP
        env:
        - name: LOAD_LATEST_SAVE
          value: "true"
        - name: DLC_SPACE_AGE
          value: "true"
        volumeMounts:
        - name: factorio-config
          mountPath: /factorio
      volumes:
      - name: factorio-config
        persistentVolumeClaim:
          claimName: factorio-config-pvc
          readOnly: false
