---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  labels:
    app: saatisfactory
  #annotations:
  #  metallb.universe.tf/allow-shared-ip: "shared-192.168.1.211"
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  selector:
    app: satisfactory
  ports:
    - name: "api"
      port: 7777
      protocol: TCP
      targetPort: 7777
    - name: "game"
      port: 7777
      protocol: UDP
      targetPort: 7777
    - name: "messaging"
      port: 8888
      protocol: TCP
      targetPort: 8888
  loadBalancerIP: 192.168.1.212
  type: LoadBalancer
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: satisfactory-config-pvc
#  namespace: default
#spec:
#  storageClassName: csi-rbd-sc
#  accessModes:
#   - ReadWriteOnce
#  resources:
#    requests:
#      storage: 20Gi
#---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: satisfactory
spec:
  selector:
    matchLabels:
      app: satisfactory # has to match .spec.template.metadata.labels
  serviceName: "satisfactory"
  replicas: 1
  template:
    metadata:
      labels:
        app: satisfactory # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 30
#      nodeSelector:
#        exclusive: "yes"
#      tolerations:
#      - key: "exclusive"
#        operator: "Equal"
#        value: "yes"
#        effect: "NoSchedule"
      containers:
      - name: satisfactory
        image: wolveix/satisfactory-server:latest
        imagePullPolicy: Always
        ports:
          #- name: sftry-7777
          #  containerPort: 7777
          #  protocol: UDP
          #
          #- name: sftry-15000
          #  containerPort: 15000
          #  protocol: UDP
          #- name: sftry-15777
          #  containerPort: 15777
          #  protocol: UDP
          - name: "api"
            containerPort: 7777
            protocol: TCP
          - name: "game"
            containerPort: 7777
            protocol: UDP
          - name: "messaging"
            containerPort: 8888
            protocol: TCP
        env:
        - name: DEBUG
          value: "false"
        - name: TZ
          value: America/Chicago
        - name: "STEAMBETA"
          value: "false"
        - name: SKIPUPDATE
          value: "false"
        - name: AUTOSAVEINTERVAL
          value: "600"
        - name: NETWORKQUALITY
          value: "5"
        - name: MAXTICKRATE
          value: "60"
        volumeMounts:
        - name: satisfactory-config
          mountPath: /config/
        - name: satisfactory-data
          mountPath: /config/gamefiles
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "/home/steam/healthcheck.sh"
          initialDelaySeconds: 300
          failureThreshold: 4
          successThreshold: 1
          periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: satisfactory-config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: satisfactory-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
