apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  destination:
    namespace: default 
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: deployments/stack/infrastructure
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - PrunePropagationPolicy=foreground
    automated:
      #prune: true
      selfHeal: true
