---
- name: delete specific file that does not allow 
  file:
    path: /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
    state: absent
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20")

- name: need to specify exact datasource type in Ubuntu 20.04
  lineinfile:
    path: /etc/cloud/cloud.cfg.d/99-installer.cfg
    regexp: '^datasource_list'
    line: 'datasource_list: [ NoCloud, None ]'
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20")
