apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    chart: homepage
    repoURL: http://jameswynn.github.io/helm-charts
    targetRevision: 2.0.2
    helm:
      releaseName: homepage
      valueFiles:
      - $homepage_values/deployments/stack/applications/homepage_values.yml
  - repoURL: 'https://github.com/dustinmhorvath/k8s_workspace.git'
    targetRevision: main
    ref: homepage_values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
