---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  # At the time of writing, immich is only compatible with pgvecto.rs <0.4. Latest postgres image with that version is 16.5.
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  instances: 1

  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;

  storage:
    size: 50Gi
    storageClass: csi-rbd-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-config-rbd
  namespace: default
spec:
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteOnce
#  volumeName: immich-config-rbd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  sources:
  - chart: immich
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: 0.*
    helm:
      releaseName: immich
      valuesObject:
        env:
          DB_HOSTNAME: immich-postgres-rw.default.svc.cluster.local
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-postgres-app
                key: password
        #postgresql:
        #  global:
        #    postgresql:
        #      auth:
        #        existingSecret: immich-postgres-user
        immich:
          persistence:
            library:
              existingClaim: immich-config-rbd
        valkey:
          enabled: true
        server:
          probes:
            startup:
              spec:
                failureThreshold: 360
          ingress: 
            main:
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
              enabled: true
              hosts:
                - host: immich.perihelion.host
                  paths:
                    - path: /
              tls:
                - hosts:
                    - immich.perihelion.host
                  secretName: immich-perihelion-host
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default

