apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: qbittorrent
  selector:
    app: qbittorrent
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: qbittorrent-downloads-pv
    nodeStageSecretRef:
      name: qbittorrent-ceph
      namespace: default
    nodePublishSecretRef:
      name: qbittorrent-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.201:6789
      rootPath: /downloads
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: qbittorrent-downloads-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: qbittorrent-config-pv
    nodeStageSecretRef:
      name: qbittorrent-ceph
      namespace: default
    nodePublishSecretRef:
      name: qbittorrent-ceph
      namespace: default
    volumeAttributes:
      monitors: 192.168.1.201
      rootPath: /containervolumes/qbittorrent
      provisionVolume: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: qbittorrent-config-pv
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent # has to match .spec.template.metadata.labels
  serviceName: "qbittorrent"
  replicas: 1
  template:
    metadata:
      labels:
        app: qbittorrent # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        env:
          - name: TZ
            value: America/Chicago
          - name: WEBUI_PORT
            value: "8080"
        ports:
        - containerPort: 8080
          name: qbittorrent
        volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: qbittorrent-downloads
          mountPath: /downloads
      volumes:
      - name: qbittorrent-config
        persistentVolumeClaim:
          claimName: qbittorrent-config-pvc
          readOnly: false
      - name: qbittorrent-downloads
        persistentVolumeClaim:
          claimName: qbittorrent-downloads-pvc
          readOnly: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  rules:
  - host: torrent.perihelion.host
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: qbittorrent
            port:
              number: 80
  tls:
  - hosts:
    - torrent.perihelion.host
    secretName: torrent.perihelion.host
